- id: '1722083061971'
  alias: test
  description: ''
  trigger:
  - platform: mqtt
    topic: HA-ESP32-02/01/state
    payload: '32'
  condition: []
  action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: 太热啦
      title: 啊啊啊
  mode: single
